### PR TITLE
Added missing metadata for podspec and web support

### PR DESCRIPTION
**Pull request by robertherber**
Cocoapods was missing some metadata so I added it. Also added web support.

### CODE REVIEW

**Comment by DimitarNestorov** [comment]
You've added more than that

**Comment by robertherber** [comment]
@dimitarnestorov That was fast! ;) Yeah, I added web support as well. Forgot to break it out into separate forks. Verified in Safari.

**Comment by robertherber** [comment]
@dimitarnestorov And I'm sure there's a better way to add the types, not very used to TypeScript and adding "dom" to lib in tsconfig rendered lots of RN-related errors. Please feel free to improve this :)

**Comment by DimitarNestorov** [comment]
Split it into two, will merge and release the podspec changes as soon as you do. Not a fan of React Native Web so I'll need other people to verify and actually request the feature, maybe open both an issue and a PR for max visibility.

**Comment by DimitarNestorov** [comment]
In `library/src/initial-mode.web.ts` you should try adding the following instead of defining types manually:
```typescript
/// <reference lib="dom" />
```

**Comment by robertherber** [comment]
@dimitarnestorov Good suggestion, I've done that now (#7 and #8). As for the lib=dom thing I get the same errors as when I tried before. Maybe you could have a look at it, with more TypeScript experience? :)

```
node_modules/@types/react-native/globals.d.ts:36:15 - error TS2300: Duplicate identifier 'FormData'.

36 declare class FormData {
                 ~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:5353:11
    5353 interface FormData {
                   ~~~~~~~~
    'FormData' was also declared here.
  ../node_modules/typescript/lib/lib.dom.d.ts:5363:13
    5363 declare var FormData: {
                     ~~~~~~~~
    and here.

node_modules/@types/react-native/globals.d.ts:81:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined', but here has type 'string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined'.

81     body?: BodyInit_;
       ~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:1413:5
    1413     body?: BodyInit | null;
             ~~~~
    'body' was also declared here.

node_modules/@types/react-native/globals.d.ts:107:14 - error TS2300: Duplicate identifier 'RequestInfo'.

107 declare type RequestInfo = Request | string;
                 ~~~~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:18568:6
    18568 type RequestInfo = Request | string;
               ~~~~~~~~~~~
    'RequestInfo' was also declared here.

node_modules/@types/react-native/globals.d.ts:126:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'Response' must be of type '{ new (body?: string | ArrayBuffer | ArrayBufferView | Blob | FormData | URLSearchParams | ReadableStream<Uint8Array> | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error(): Response; redirect(url: string, status?: number | undefined): Response; }', but here has type '{ new (body?: string | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | Blob | FormData | null | undefined, init?: ResponseInit | undefined): Response; prototype: Response; error: () => Response; redirect: (url: ...'.

126 declare var Response: {
                ~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:12463:13
    12463 declare var Response: {
                      ~~~~~~~~
    'Response' was also declared here.

node_modules/@types/react-native/globals.d.ts:249:14 - error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.

249 declare type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:18746:6
    18746 type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
               ~~~~~~~~~~~~~~~~~~~~~~~~~~
    'XMLHttpRequestResponseType' was also declared here.

node_modules/@types/react-native/index.d.ts:9412:18 - error TS2717: Subsequent property declarations must have the same type.  Property 'geolocation' must be of type 'Geolocation', but here has type 'GeolocationStatic'.

9412         readonly geolocation: Geolocation;
                      ~~~~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:10581:14
    10581     readonly geolocation: Geolocation;
                       ~~~~~~~~~~~
    'geolocation' was also declared here.

node_modules/@types/react-native/index.d.ts:9415:11 - error TS2451: Cannot redeclare block-scoped variable 'navigator'.

9415     const navigator: Navigator;
               ~~~~~~~~~

  ../node_modules/typescript/lib/lib.dom.d.ts:18152:13
    18152 declare var navigator: Navigator;
                      ~~~~~~~~~
    'navigator' was also declared here.

../node_modules/typescript/lib/lib.dom.d.ts:5353:11 - error TS2300: Duplicate identifier 'FormData'.

5353 interface FormData {
               ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.

../node_modules/typescript/lib/lib.dom.d.ts:5363:13 - error TS2300: Duplicate identifier 'FormData'.

5363 declare var FormData: {
                 ~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:36:15
    36 declare class FormData {
                     ~~~~~~~~
    'FormData' was also declared here.

../node_modules/typescript/lib/lib.dom.d.ts:17123:11 - error TS2320: Interface 'Window' cannot simultaneously extend types 'GlobalFetch' and 'WindowOrWorkerGlobalScope'.
  Named property 'fetch' of types 'GlobalFetch' and 'WindowOrWorkerGlobalScope' are not identical.

17123 interface Window extends EventTarget, WindowTimers, WindowSessionStorage, WindowLocalStorage, WindowConsole, GlobalEventHandlers, IDBEnvironment, WindowBase64, GlobalFetch, WindowOrWorkerGlobalScope, WindowEventHandlers {
                ~~~~~~

../node_modules/typescript/lib/lib.dom.d.ts:18152:13 - error TS2451: Cannot redeclare block-scoped variable 'navigator'.

18152 declare var navigator: Navigator;
                  ~~~~~~~~~

  node_modules/@types/react-native/index.d.ts:9415:11
    9415     const navigator: Navigator;
                   ~~~~~~~~~
    'navigator' was also declared here.

../node_modules/typescript/lib/lib.dom.d.ts:18568:6 - error TS2300: Duplicate identifier 'RequestInfo'.

18568 type RequestInfo = Request | string;
           ~~~~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:107:14
    107 declare type RequestInfo = Request | string;
                     ~~~~~~~~~~~
    'RequestInfo' was also declared here.

../node_modules/typescript/lib/lib.dom.d.ts:18746:6 - error TS2300: Duplicate identifier 'XMLHttpRequestResponseType'.

18746 type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react-native/globals.d.ts:249:14
    249 declare type XMLHttpRequestResponseType = "" | "arraybuffer" | "blob" | "document" | "json" | "text";
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    'XMLHttpRequestResponseType' was also declared here.


Found 13 errors.
```

**Pull request closed without merging**
